const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const fmt=(n,d=2)=>Number(n||0).toLocaleString('en-US',{maximumFractionDigits:d});
const money=n=>`$ ${fmt(n,2)}`;
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,6);

const seedProducts=[
 {id:uid(),cat:'inverter',brand:'Deye',model:'SUN-6K-SG04LP1-EU',name:'Deye 6kW Hybrid LV 1P',power:6,maxPv:7.8,mpptMin:150,mpptMax:425,maxVoc:500,mppts:2,inputCurrent:13,battery:'40-60V',cost:1050,sell:1300,stock:4},
 {id:uid(),cat:'inverter',brand:'Deye',model:'SUN-12K-SG04LP3-EU',name:'Deye 12kW Hybrid LV 3P',power:12,maxPv:15.6,mpptMin:200,mpptMax:650,maxVoc:800,mppts:2,inputCurrent:26,battery:'40-60V',cost:2500,sell:2950,stock:2},
 {id:uid(),cat:'inverter',brand:'Deye',model:'SUN-50K-SG01HP3-EU',name:'Deye 50kW Hybrid HV 3P',power:50,maxPv:65,mpptMin:150,mpptMax:850,maxVoc:1000,mppts:4,inputCurrent:36,battery:'160-800V',cost:7600,sell:8900,stock:1},
 {id:uid(),cat:'panel',brand:'LONGi',model:'LR7-72HGD-620M',name:'LONGi Hi-MO 7 620W',watts:620,voc:52.3,vmp:44.2,isc:15.1,imp:14.03,length:2382,width:1134,weight:33.5,cost:91,sell:116,stock:240},
 {id:uid(),cat:'panel',brand:'LONGi',model:'LR7-72HVH-645M',name:'LONGi Hi-MO X10 645W',watts:645,voc:53.1,vmp:45.1,isc:15.35,imp:14.31,length:2382,width:1134,weight:28.5,cost:105,sell:132,stock:120},
 {id:uid(),cat:'panel',brand:'JA Solar',model:'JAM72D42-625/LB',name:'JA Solar 625W Bifacial',watts:625,voc:52.1,vmp:44.1,isc:15.2,imp:14.18,length:2333,width:1134,weight:32.5,cost:88,sell:112,stock:300},
 {id:uid(),cat:'battery',brand:'Deye',model:'SE-G5.1 Pro-B',name:'Deye 5.12kWh LV Battery',kwh:5.12,usable:4.6,voltage:'51.2V',maxCurrent:100,cost:940,sell:1175,stock:18},
 {id:uid(),cat:'battery',brand:'Deye',model:'BOS-G',name:'Deye BOS-G HV Module 5.12kWh',kwh:5.12,usable:4.6,voltage:'51.2V module',maxCurrent:100,cost:970,sell:1220,stock:30},
 {id:uid(),cat:'dc',brand:'Suntree',model:'SUP2H-PV 2P',name:'DC SPD Type 2 1000V',cost:32,sell:48,stock:40},
 {id:uid(),cat:'dc',brand:'Suntree',model:'SL7-63 2P 32A',name:'DC MCB 2P 32A 1000V',cost:18,sell:29,stock:60},
 {id:uid(),cat:'cable',brand:'Suntree',model:'PV1-F 6mm²',name:'Solar DC Cable 6mm² / meter',cost:.58,sell:.9,stock:2500}
];

const defaultState={projects:[],products:seedProducts,settings:{company:'iCOOL Trading & Contracting',phone:'03715512',currency:'USD',laborRate:0.08,overhead:0.05,profit:0.18,tax:0},activeProject:null};
let state=load();
let current='dashboard';
function load(){try{return {...defaultState,...JSON.parse(localStorage.getItem('icoolSolarPro')||'{}')}}catch{return structuredClone(defaultState)}}
function save(){localStorage.setItem('icoolSolarPro',JSON.stringify(state))}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function getProject(){return state.projects.find(p=>p.id===state.activeProject)}
function ensureProject(){if(!getProject()){newProject();return false}return true}

const navItems=[['dashboard','▦','لوحة التحكم'],['projects','◫','المشاريع والعملاء'],['survey','⌖','كشف الموقع'],['loads','⚡','تحليل الأحمال'],['designer','☀','تصميم النظام'],['structure','⌂','الهيكل المعدني'],['quote','＄','عرض السعر والكلفة'],['report','▤','التقرير ودراسة الجدوى'],['library','▥','مكتبة المنتجات'],['settings','⚙','الإعدادات']];
function renderNav(){ $('#nav').innerHTML=navItems.map(([id,ic,n])=>`<button class="nav-btn ${id===current?'active':''}" data-page="${id}"><span>${ic}</span>${n}</button>`).join(''); $$('.nav-btn').forEach(b=>b.onclick=()=>go(b.dataset.page)); }
function go(page){current=page;renderNav(); $('.sidebar').classList.remove('open'); const meta={dashboard:['لوحة التحكم','ملخص الأعمال والمشاريع'],projects:['المشاريع والعملاء','إدارة ملفات الزبائن'],survey:['كشف الموقع','تسجيل المعطيات الكهربائية ومساحة التركيب'],loads:['تحليل الأحمال','حساب الاستهلاك والذروة'],designer:['تصميم النظام','اختيار الألواح والإنفرتر والبطاريات'],structure:['تصميم الهيكل المعدني','مخطط أولي وكميات الحديد'],quote:['عرض السعر والكلفة','فصل كلفة الشركة عن سعر الزبون'],report:['التقرير ودراسة الجدوى','الإنتاج والتوفير وفترة الاسترداد'],library:['مكتبة المنتجات','Deye وLONGi وJA Solar وSuntree'],settings:['الإعدادات','بيانات الشركة ونسب التسعير']}[page]; $('#pageTitle').textContent=meta[0];$('#pageSubtitle').textContent=meta[1]; render();}
function render(){({dashboard,projects,survey,loads,designer,structure,quote,report,library,settings}[current]||dashboard)()}
function activeBanner(){const p=getProject();return p?`<div class="card" style="margin-bottom:16px"><b>المشروع الحالي:</b> ${p.client||'بدون اسم'} — ${p.site||'الموقع غير محدد'} <span class="badge">${p.status||'دراسة'}</span></div>`:`<div class="card empty">لا يوجد مشروع محدد. أنشئ مشروعًا جديدًا أولًا.</div>`}

function newProject(){const p={id:uid(),client:'',phone:'',site:'',date:new Date().toISOString().slice(0,10),status:'كشف أولي',systemType:'Hybrid',phase:'3P',gridHours:4,generatorKva:0,roofType:'Concrete',roofL:20,roofW:10,azimuth:180,tilt:15,cableDc:30,cableAc:15,loads:[],design:{},structure:{},quote:{discount:0,tax:0},notes:''};state.projects.unshift(p);state.activeProject=p.id;save();go('survey');toast('تم إنشاء مشروع جديد')}

function dashboard(){const total=state.projects.length, accepted=state.projects.filter(p=>['مقبول','قيد التنفيذ','منجز'].includes(p.status)).length;const revenue=state.projects.reduce((s,p)=>s+(p.quote?.sellTotal||0),0);const profit=state.projects.reduce((s,p)=>s+(p.quote?.profit||0),0);$('#content').innerHTML=`
<div class="hero"><div><h2>من الكشف إلى التسليم في ملف واحد</h2><p>أنشئ دراسة فنية، BOQ، عرض سعر، جدوى ومخطط تركيب أولي.</p></div><button class="primary" onclick="newProject()">+ بدء كشف جديد</button></div>
<div class="grid grid-4" style="margin-top:16px">
${[['المشاريع',total],['المقبولة',accepted],['قيمة العروض',money(revenue)],['الربح المتوقع',money(profit)]].map(x=>`<div class="card stat"><div><div class="label">${x[0]}</div><div class="num">${x[1]}</div></div><div style="font-size:28px;color:var(--orange)">●</div></div>`).join('')}</div>
<div class="grid grid-2" style="margin-top:16px"><div class="card"><div class="section-title"><h2>آخر المشاريع</h2><button class="secondary" onclick="go('projects')">عرض الكل</button></div>${state.projects.slice(0,5).map(p=>`<div class="project-card" onclick="openProject('${p.id}')" style="padding:12px 0;border-bottom:1px solid var(--line)"><b>${p.client||'مشروع جديد'}</b><div class="muted">${p.site||'—'} · ${p.date}</div></div>`).join('')||'<div class="empty">لا توجد مشاريع بعد</div>'}</div>
<div class="card"><div class="section-title"><h2>حالة مكتبة المواد</h2><span class="badge">${state.products.length} مادة</span></div>${['inverter','panel','battery','dc','cable'].map(c=>{const n=state.products.filter(x=>x.cat===c).length;return `<div style="margin:15px 0"><div style="display:flex;justify-content:space-between"><span>${{inverter:'إنفرترات',panel:'ألواح',battery:'بطاريات',dc:'حمايات DC',cable:'كابلات'}[c]}</span><b>${n}</b></div><div class="progress"><i style="width:${Math.min(100,n*15)}%"></i></div></div>`}).join('')}</div></div>`}
function projects(){ $('#content').innerHTML=`<div class="card"><div class="section-title"><h2>المشاريع</h2><button class="primary" onclick="newProject()">+ مشروع جديد</button></div><div class="table-wrap"><table><thead><tr><th>الزبون</th><th>الموقع</th><th>التاريخ</th><th>النظام</th><th>الحالة</th><th>قيمة العرض</th><th></th></tr></thead><tbody>${state.projects.map(p=>`<tr><td><b>${p.client||'—'}</b><br><span class="muted">${p.phone||''}</span></td><td>${p.site||'—'}</td><td>${p.date}</td><td>${p.systemType}</td><td><span class="badge">${p.status}</span></td><td>${money(p.quote?.sellTotal||0)}</td><td><button class="secondary" onclick="openProject('${p.id}')">فتح</button> <button class="danger-btn" onclick="deleteProject('${p.id}')">حذف</button></td></tr>`).join('')||'<tr><td colspan="7" class="empty">لا توجد مشاريع</td></tr>'}</tbody></table></div></div>`}
window.openProject=id=>{state.activeProject=id;save();go('survey')};window.deleteProject=id=>{if(confirm('حذف المشروع؟')){state.projects=state.projects.filter(p=>p.id!==id);if(state.activeProject===id)state.activeProject=null;save();projects()}};

function survey(){if(!ensureProject())return;const p=getProject();$('#content').innerHTML=activeBanner()+`<div class="card"><div class="section-title"><h2>بيانات الزبون والموقع</h2><span class="badge">يحفظ تلقائيًا</span></div><div class="form-grid">
${field('client','اسم الزبون',p.client)}${field('phone','رقم الهاتف',p.phone)}${field('site','الموقع / البلدة',p.site)}${field('date','تاريخ الكشف',p.date,'date')}
${select('status','حالة المشروع',['كشف أولي','قيد الدراسة','عرض سعر','مقبول','قيد التنفيذ','منجز'],p.status)}${select('systemType','نوع النظام',['On-Grid','Hybrid','Off-Grid'],p.systemType)}${select('phase','التغذية',['1P','3P'],p.phase)}${field('gridHours','ساعات كهرباء الشبكة يوميًا',p.gridHours,'number')}
${field('generatorKva','قدرة المولد kVA',p.generatorKva,'number')}${select('roofType','نوع السطح',['Concrete','Metal','Tile','Ground'],p.roofType)}${field('roofL','طول المساحة m',p.roofL,'number')}${field('roofW','عرض المساحة m',p.roofW,'number')}
${field('azimuth','اتجاه السطح °',p.azimuth,'number')}${field('tilt','زاوية الميل °',p.tilt,'number')}${field('cableDc','مسار كابل DC m',p.cableDc,'number')}${field('cableAc','مسار كابل AC m',p.cableAc,'number')}
<div class="field span-4"><label>ملاحظات الموقع</label><textarea data-bind="notes">${p.notes||''}</textarea></div></div><div class="actions"><button class="primary" onclick="saveSurvey()">حفظ ومتابعة الأحمال</button><button class="secondary" onclick="go('loads')">التالي</button></div></div>`; bindProjectInputs()}
function field(k,l,v,t='text'){return `<div class="field"><label>${l}</label><input data-bind="${k}" type="${t}" value="${v??''}"></div>`}function select(k,l,arr,v){return `<div class="field"><label>${l}</label><select data-bind="${k}">${arr.map(x=>`<option ${x===v?'selected':''}>${x}</option>`).join('')}</select></div>`}
function bindProjectInputs(){$$('[data-bind]').forEach(el=>el.onchange=()=>{const p=getProject();p[el.dataset.bind]=el.type==='number'?Number(el.value):el.value;save()})}window.saveSurvey=()=>{bindProjectInputs();save();go('loads')};

function loads(){if(!ensureProject())return;const p=getProject();const totals=loadTotals(p);$('#content').innerHTML=activeBanner()+`<div class="card"><div class="section-title"><h2>جدول الأحمال</h2><button class="primary" onclick="addLoad()">+ إضافة حمل</button></div><div class="table-wrap"><table><thead><tr><th>الجهاز</th><th>العدد</th><th>W</th><th>ساعات نهار</th><th>ساعات ليل</th><th>Surge ×</th><th>kWh/day</th><th></th></tr></thead><tbody>${p.loads.map((l,i)=>`<tr><td><input value="${l.name}" onchange="editLoad(${i},'name',this.value)"></td><td><input class="small-input" type="number" value="${l.qty}" onchange="editLoad(${i},'qty',this.value)"></td><td><input class="small-input" type="number" value="${l.watts}" onchange="editLoad(${i},'watts',this.value)"></td><td><input class="small-input" type="number" value="${l.day}" onchange="editLoad(${i},'day',this.value)"></td><td><input class="small-input" type="number" value="${l.night}" onchange="editLoad(${i},'night',this.value)"></td><td><input class="small-input" type="number" step=".1" value="${l.surge}" onchange="editLoad(${i},'surge',this.value)"></td><td>${fmt(l.qty*l.watts*(l.day+l.night)/1000)}</td><td><button class="danger-btn" onclick="removeLoad(${i})">×</button></td></tr>`).join('')||'<tr><td colspan="8" class="empty">أضف الأحمال الكهربائية</td></tr>'}</tbody></table></div>
<div class="kpi-row">${[['الحمل المتصل',fmt(totals.connected)+' kW'],['ذروة بدء تقريبية',fmt(totals.peak)+' kW'],['استهلاك النهار',fmt(totals.day)+' kWh'],['الاستهلاك اليومي',fmt(totals.total)+' kWh']].map(x=>`<div class="summary-box"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('')}</div><div class="actions"><button class="primary" onclick="go('designer')">تصميم النظام المقترح</button></div></div>`}
function loadTotals(p){return p.loads.reduce((a,l)=>{const kw=l.qty*l.watts/1000;a.connected+=kw;a.peak+=kw*l.surge;a.day+=kw*l.day;a.night+=kw*l.night;a.total+=kw*(l.day+l.night);return a},{connected:0,peak:0,day:0,night:0,total:0})}
window.addLoad=()=>{const p=getProject();p.loads.push({name:'حمل جديد',qty:1,watts:1000,day:4,night:2,surge:1});save();loads()};window.editLoad=(i,k,v)=>{const p=getProject();p.loads[i][k]=k==='name'?v:Number(v);save();loads()};window.removeLoad=i=>{getProject().loads.splice(i,1);save();loads()};

function designer(){if(!ensureProject())return;const p=getProject(),t=loadTotals(p);const panels=state.products.filter(x=>x.cat==='panel'),invs=state.products.filter(x=>x.cat==='inverter'),bats=state.products.filter(x=>x.cat==='battery');const d=p.design||{};$('#content').innerHTML=activeBanner()+`<div class="grid grid-2"><div class="card"><div class="section-title"><h2>مدخلات التصميم</h2></div><div class="form-grid">
${selectD('panelId','اللوح',panels,d.panelId)}${selectD('inverterId','الإنفرتر',invs,d.inverterId)}${selectD('batteryId','البطارية',bats,d.batteryId)}${fieldD('backupHours','ساعات الاستقلالية المطلوبة',d.backupHours||4)}
${fieldD('sunHours','Peak Sun Hours',d.sunHours||5.5)}${fieldD('losses','خسائر النظام %',d.losses??18)}${fieldD('minSoc','Minimum SOC %',d.minSoc??20)}${fieldD('panelCount','عدد ألواح يدوي (0=تلقائي)',d.panelCount||0)}
</div><div class="actions"><button class="primary" onclick="calculateDesign()">احسب التصميم</button></div></div><div class="card"><div class="section-title"><h2>ملخص الأحمال</h2></div><div class="kpi-row" style="grid-template-columns:repeat(2,1fr)"><div class="summary-box">الاستهلاك اليومي<strong>${fmt(t.total)} kWh</strong></div><div class="summary-box">الحمل المتصل<strong>${fmt(t.connected)} kW</strong></div><div class="summary-box">استهلاك الليل<strong>${fmt(t.night)} kWh</strong></div><div class="summary-box">ذروة تقريبية<strong>${fmt(t.peak)} kW</strong></div></div></div></div><div id="designResults" style="margin-top:16px">${d.results?designResultHtml(d.results):''}</div>`}
function selectD(k,l,arr,v){return `<div class="field span-2"><label>${l}</label><select id="${k}">${arr.map(x=>`<option value="${x.id}" ${x.id===v?'selected':''}>${x.name} — ${x.model}</option>`).join('')}</select></div>`}function fieldD(k,l,v){return `<div class="field"><label>${l}</label><input id="${k}" type="number" step=".1" value="${v}"></div>`}
window.calculateDesign=()=>{const p=getProject(),t=loadTotals(p);if(!t.total){toast('أدخل الأحمال أولًا');return}const panel=state.products.find(x=>x.id===$('#panelId').value),inv=state.products.find(x=>x.id===$('#inverterId').value),bat=state.products.find(x=>x.id===$('#batteryId').value);const sun=Number($('#sunHours').value),loss=Number($('#losses').value)/100,backup=Number($('#backupHours').value),minSoc=Number($('#minSoc').value)/100;let count=Number($('#panelCount').value)||Math.ceil(t.total/(panel.watts/1000*sun*(1-loss)));count=Math.max(count,Math.ceil(inv.power*1.05/(panel.watts/1000)));const pv=count*panel.watts/1000;const daily=pv*sun*(1-loss);const usableNeeded=t.night*(backup/Math.max(1,p.loads.reduce((s,l)=>s+l.night,0)/Math.max(1,p.loads.length)))||t.connected*backup;const batCount=Math.max(p.systemType==='On-Grid'?0:1,Math.ceil(usableNeeded/(bat.kwh*(1-minSoc))));const perString=Math.min(Math.floor(inv.maxVoc/panel.voc)-1,Math.floor(inv.mpptMax/panel.vmp));const strings=Math.ceil(count/perString);const dcac=pv/inv.power;const voltageOk=perString*panel.voc<inv.maxVoc&&perString*panel.vmp>=inv.mpptMin;const powerOk=pv<=inv.maxPv;const invLoadOk=inv.power>=t.connected*.8;const r={panelId:panel.id,inverterId:inv.id,batteryId:bat.id,panelCount:count,pv,daily,monthly:daily*30,annual:daily*365,batCount,batteryKwh:batCount*bat.kwh,usableBattery:batCount*bat.kwh*(1-minSoc),perString,strings,dcac,voltageOk,powerOk,invLoadOk,coverage:Math.min(100,daily/t.total*100),panel,inv,bat};p.design={panelId:panel.id,inverterId:inv.id,batteryId:bat.id,backupHours:backup,sunHours:sun,losses:Number($('#losses').value),minSoc:Number($('#minSoc').value),panelCount:Number($('#panelCount').value),results:r};save();$('#designResults').innerHTML=designResultHtml(r);toast('تم حساب التصميم')}
function designResultHtml(r){return `<div class="card"><div class="section-title"><h2>التصميم المقترح</h2><span class="badge">نتيجة أولية قابلة للتعديل</span></div><div class="grid grid-4">${[['قدرة الألواح',fmt(r.pv)+' kWp'],['الإنتاج اليومي',fmt(r.daily)+' kWh'],['عدد البطاريات',r.batCount],['تغطية الاستهلاك',fmt(r.coverage,0)+'%']].map(x=>`<div class="summary-box"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('')}</div><div class="table-wrap" style="margin-top:15px"><table><tbody><tr><th>الألواح</th><td>${r.panelCount} × ${r.panel.name}</td></tr><tr><th>الإنفرتر</th><td>${r.inv.name}</td></tr><tr><th>البطاريات</th><td>${r.batCount?`${r.batCount} × ${r.bat.name} = ${fmt(r.batteryKwh)} kWh`:'لا توجد بطاريات'}</td></tr><tr><th>String Design</th><td>${r.strings} Strings × نحو ${r.perString} ألواح</td></tr><tr><th>DC/AC Ratio</th><td>${fmt(r.dcac)}</td></tr><tr><th>فحص الجهد</th><td class="${r.voltageOk?'status-ok':'status-bad'}">${r.voltageOk?'مطابق':'راجع عدد الألواح في String'}</td></tr><tr><th>فحص PV Power</th><td class="${r.powerOk?'status-ok':'status-bad'}">${r.powerOk?'مطابق':'قدرة DC تتجاوز حد الإنفرتر'}</td></tr><tr><th>ملاءمة قدرة الإنفرتر</th><td class="${r.invLoadOk?'status-ok':'status-warn'}">${r.invLoadOk?'مقبولة':'قدرة الحمل مرتفعة؛ راجع التزامن'}</td></tr></tbody></table></div><div class="actions"><button class="primary" onclick="buildQuote()">إنشاء BOQ وعرض السعر</button><button class="secondary" onclick="go('structure')">تصميم الهيكل</button></div></div>`}

function structure(){if(!ensureProject())return;const p=getProject(),r=p.design?.results;if(!r){$('#content').innerHTML=activeBanner()+`<div class="card empty">احسب تصميم النظام أولًا.</div>`;return}const s=p.structure||{};$('#content').innerHTML=activeBanner()+`<div class="grid grid-2"><div class="card"><div class="section-title"><h2>مدخلات الهيكل</h2></div><div class="form-grid">${selectS('orientation','اتجاه اللوح',['Portrait','Landscape'],s.orientation||'Portrait')}${fieldS('rows','عدد الصفوف',s.rows||Math.ceil(Math.sqrt(r.panelCount)))}${fieldS('frontHeight','ارتفاع المقدمة cm',s.frontHeight||40)}${fieldS('tilt','الميل °',s.tilt||p.tilt||15)}${fieldS('rowGap','ممر بين الصفوف cm',s.rowGap||80)}${fieldS('postSpacing','المسافة بين الأعمدة m',s.postSpacing||2.5)}${fieldS('steelKgM2','حديد تقريبي kg/m²',s.steelKgM2||8)}${fieldS('steelCostKg','كلفة الحديد $/kg',s.steelCostKg||1.15)}</div><div class="actions"><button class="primary" onclick="drawStructure()">إنشاء المخطط والكميات</button></div></div><div class="card"><div class="section-title"><h2>المخطط الأولي</h2><span class="badge">Top + pseudo 3D</span></div><div class="canvas-wrap"><canvas id="structureCanvas" width="900" height="560"></canvas></div></div></div><div id="structureSummary" style="margin-top:16px"></div>`;setTimeout(()=>drawStructure(false),50)}
function selectS(k,l,a,v){return `<div class="field"><label>${l}</label><select id="${k}">${a.map(x=>`<option ${x===v?'selected':''}>${x}</option>`).join('')}</select></div>`}function fieldS(k,l,v){return `<div class="field"><label>${l}</label><input id="${k}" type="number" step=".1" value="${v}"></div>`}
window.drawStructure=(persist=true)=>{const p=getProject(),r=p.design.results,canvas=$('#structureCanvas');if(!canvas)return;const ctx=canvas.getContext('2d');const orientation=$('#orientation').value,rows=Math.max(1,Number($('#rows').value)),frontHeight=Number($('#frontHeight').value),tilt=Number($('#tilt').value),rowGap=Number($('#rowGap').value),postSpacing=Number($('#postSpacing').value),steelKgM2=Number($('#steelKgM2').value),steelCostKg=Number($('#steelCostKg').value);const cols=Math.ceil(r.panelCount/rows),pw=orientation==='Portrait'?70:120,ph=orientation==='Portrait'?120:70;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#f5f8fa';ctx.fillRect(0,0,900,560);ctx.fillStyle='#0b2740';ctx.font='bold 22px Arial';ctx.fillText('iCOOL Solar Structure Layout',30,35);let n=0;for(let rr=0;rr<rows;rr++){for(let c=0;c<cols&&n<r.panelCount;c++,n++){const x=45+c*(pw+10),y=65+rr*(ph+25);ctx.fillStyle='#174e78';ctx.fillRect(x,y,pw,ph);ctx.strokeStyle='#9ec6df';ctx.strokeRect(x+4,y+4,pw-8,ph-8);ctx.strokeStyle='#fff';ctx.beginPath();ctx.moveTo(x+pw/2,y);ctx.lineTo(x+pw/2,y+ph);ctx.moveTo(x,y+ph/2);ctx.lineTo(x+pw,y+ph/2);ctx.stroke()}}
ctx.fillStyle='#5d6f7b';ctx.font='16px Arial';ctx.fillText(`${r.panelCount} panels · ${rows} rows · ${cols} columns · ${orientation}`,30,535);const panelArea=r.panelCount*(r.panel.length/1000)*(r.panel.width/1000);const steelKg=panelArea*steelKgM2,steelCost=steelKg*steelCostKg;const posts=Math.ceil((cols*(orientation==='Portrait'?r.panel.width:r.panel.length)/1000)/postSpacing+1)*rows;const s={orientation,rows,cols,frontHeight,tilt,rowGap,postSpacing,steelKgM2,steelCostKg,panelArea,steelKg,steelCost,posts};if(persist){p.structure=s;save();toast('تم تحديث مخطط الهيكل')}$('#structureSummary').innerHTML=`<div class="card"><div class="section-title"><h2>كميات أولية للهيكل</h2><span class="status-warn">تحتاج مراجعة مهندس إنشائي</span></div><div class="grid grid-4"><div class="summary-box">مساحة الألواح<strong>${fmt(panelArea)} m²</strong></div><div class="summary-box">وزن الحديد التقريبي<strong>${fmt(steelKg)} kg</strong></div><div class="summary-box">عدد الأعمدة التقريبي<strong>${posts}</strong></div><div class="summary-box">كلفة الحديد التقريبية<strong>${money(steelCost)}</strong></div></div><p class="muted">المخطط يولّد توزيعًا وكميات مبدئية. اختيار المقاطع والأنكر ومقاومة الرياح والتوقيع الإنشائي يجب أن يتم بعد معاينة تفاصيل السطح.</p></div>`}

function buildBOQ(p){const r=p.design.results,s=p.structure||{};const dcCable=Math.ceil((p.cableDc||0)*2*1.15);const acCable=Math.ceil((p.cableAc||0)*1.15);return [
 {name:r.panel.name,qty:r.panelCount,unit:'pcs',cost:r.panel.cost,sell:r.panel.sell},
 {name:r.inv.name,qty:1,unit:'pcs',cost:r.inv.cost,sell:r.inv.sell},
 ...(r.batCount?[{name:r.bat.name,qty:r.batCount,unit:'pcs',cost:r.bat.cost,sell:r.bat.sell}]:[]),
 {name:'Suntree DC Protection Set',qty:Math.max(1,r.strings),unit:'set',cost:80,sell:125},
 {name:'Suntree PV Cable 6mm²',qty:dcCable,unit:'m',cost:.58,sell:.9},
 {name:'AC protection panel and cable allowance',qty:1,unit:'lot',cost:Math.max(250,r.inv.power*35+acCable*4),sell:Math.max(380,r.inv.power*50+acCable*6)},
 {name:'Steel structure fabrication',qty:1,unit:'lot',cost:s.steelCost||r.panelCount*35,sell:(s.steelCost||r.panelCount*35)*1.3},
 {name:'Installation, testing and commissioning',qty:1,unit:'lot',cost:Math.max(350,r.pv*80),sell:Math.max(550,r.pv*115)}
]}
window.buildQuote=()=>{if(!getProject().design?.results){toast('احسب التصميم أولًا');return}const p=getProject();p.quote.items=buildBOQ(p);save();go('quote')}
function quote(){if(!ensureProject())return;const p=getProject();if(!p.design?.results){$('#content').innerHTML=activeBanner()+`<div class="card empty">احسب تصميم النظام أولًا.</div>`;return}if(!p.quote.items)p.quote.items=buildBOQ(p);calcQuote(p);$('#content').innerHTML=activeBanner()+`<div class="card"><div class="section-title"><h2>Bill of Quantities</h2><span class="badge">الكلفة الداخلية مخفية عن نسخة الزبون</span></div><div class="table-wrap"><table><thead><tr><th>البند</th><th>الكمية</th><th>الوحدة</th><th class="internal">كلفة الوحدة</th><th>سعر الوحدة</th><th class="internal">الكلفة</th><th>الإجمالي</th></tr></thead><tbody>${p.quote.items.map((x,i)=>`<tr><td><input value="${x.name}" onchange="editQuoteItem(${i},'name',this.value)"></td><td><input class="small-input" type="number" step=".1" value="${x.qty}" onchange="editQuoteItem(${i},'qty',this.value)"></td><td>${x.unit}</td><td class="internal"><input class="small-input" type="number" step=".01" value="${x.cost}" onchange="editQuoteItem(${i},'cost',this.value)"></td><td><input class="small-input" type="number" step=".01" value="${x.sell}" onchange="editQuoteItem(${i},'sell',this.value)"></td><td class="internal">${money(x.qty*x.cost)}</td><td>${money(x.qty*x.sell)}</td></tr>`).join('')}</tbody></table></div>
<div class="grid grid-2" style="margin-top:16px"><div class="card" style="box-shadow:none"><div class="form-grid">${fieldQ('discount','حسم $',p.quote.discount||0)}${fieldQ('tax','TVA %',p.quote.tax||0)}</div><div class="actions"><button class="secondary" onclick="addQuoteItem()">+ بند إضافي</button><button class="primary" onclick="updateQuote()">تحديث الحساب</button><button class="secondary" onclick="customerPrint()">طباعة نسخة الزبون</button></div></div><div class="card" style="box-shadow:none"><div class="grid grid-2"><div><span class="muted">الكلفة الداخلية</span><div class="quote-total internal">${money(p.quote.costTotal)}</div></div><div><span class="muted">سعر الزبون</span><div class="quote-total">${money(p.quote.sellTotal)}</div></div><div><span class="muted">الربح</span><strong class="status-ok">${money(p.quote.profit)}</strong></div><div><span class="muted">هامش الربح</span><strong>${fmt(p.quote.margin,1)}%</strong></div></div></div></div></div>`}
function fieldQ(k,l,v){return `<div class="field"><label>${l}</label><input id="q_${k}" type="number" step=".01" value="${v}"></div>`}function calcQuote(p){const cost=p.quote.items.reduce((s,x)=>s+x.qty*x.cost,0),base=p.quote.items.reduce((s,x)=>s+x.qty*x.sell,0),discount=Number(p.quote.discount||0),tax=Number(p.quote.tax||0);const before=Math.max(0,base-discount),sell=before*(1+tax/100);Object.assign(p.quote,{costTotal:cost,baseTotal:base,sellTotal:sell,profit:sell-cost,margin:sell?(sell-cost)/sell*100:0});save()}
window.editQuoteItem=(i,k,v)=>{const p=getProject();p.quote.items[i][k]=k==='name'?v:Number(v);calcQuote(p);quote()};window.addQuoteItem=()=>{getProject().quote.items.push({name:'بند إضافي',qty:1,unit:'lot',cost:0,sell:0});save();quote()};window.updateQuote=()=>{const p=getProject();p.quote.discount=Number($('#q_discount').value);p.quote.tax=Number($('#q_tax').value);calcQuote(p);quote();toast('تم تحديث عرض السعر')};window.customerPrint=()=>{document.body.classList.add('customer-print');$$('.internal').forEach(x=>x.style.display='none');window.print();setTimeout(()=>{$$('.internal').forEach(x=>x.style.display='');document.body.classList.remove('customer-print')},300)};

function report(){if(!ensureProject())return;const p=getProject(),r=p.design?.results;if(!r){$('#content').innerHTML=activeBanner()+`<div class="card empty">احسب التصميم أولًا.</div>`;return}calcQuote(p);const q=p.quote;const tariff=p.report?.tariff||.25, escalation=p.report?.escalation||5, maintenance=p.report?.maintenance||1;const annualSaving=r.annual*tariff,netAnnual=annualSaving-q.sellTotal*(maintenance/100),payback=netAnnual>0?q.sellTotal/netAnnual:0,co2=r.annual*.45/1000;$('#content').innerHTML=activeBanner()+`<div id="printReport"><div class="card"><div class="section-title"><div><h2>التقرير الفني ودراسة الجدوى</h2><div class="muted">${p.client} — ${p.site}</div></div><span class="badge">${p.systemType}</span></div><div class="grid grid-4"><div class="summary-box">قدرة النظام<strong>${fmt(r.pv)} kWp</strong></div><div class="summary-box">إنتاج سنوي<strong>${fmt(r.annual,0)} kWh</strong></div><div class="summary-box">بطاريات<strong>${fmt(r.batteryKwh)} kWh</strong></div><div class="summary-box">قيمة المشروع<strong>${money(q.sellTotal)}</strong></div></div></div>
<div class="grid grid-2" style="margin-top:16px"><div class="card"><h2>وصف النظام</h2><p>النظام المقترح يتألف من <b>${r.panelCount}</b> لوحًا من نوع ${r.panel.name} مع إنفرتر ${r.inv.name}${r.batCount?` وبطاريات عدد ${r.batCount} من نوع ${r.bat.name}`:''}. القدرة الإجمالية للألواح ${fmt(r.pv)} kWp، والإنتاج المتوقع نحو ${fmt(r.daily)} kWh يوميًا وفق المدخلات الحالية.</p><table><tbody><tr><th>التغطية النظرية</th><td>${fmt(r.coverage,0)}%</td></tr><tr><th>عدد Strings</th><td>${r.strings}</td></tr><tr><th>ألواح / String</th><td>نحو ${r.perString}</td></tr><tr><th>الطاقة القابلة للاستخدام</th><td>${fmt(r.usableBattery)} kWh</td></tr></tbody></table></div><div class="card no-print"><h2>فرضيات الجدوى</h2><div class="form-grid" style="grid-template-columns:1fr">${fieldR('tariff','كلفة الكهرباء البديلة $/kWh',tariff)}${fieldR('escalation','ارتفاع سعر الطاقة سنويًا %',escalation)}${fieldR('maintenance','صيانة سنوية % من الاستثمار',maintenance)}</div><button class="primary" style="margin-top:12px" onclick="updateReport()">تحديث الجدوى</button></div></div>
<div class="card" style="margin-top:16px"><div class="section-title"><h2>نتائج الجدوى</h2></div><div class="grid grid-4"><div class="summary-box">توفير سنوي إجمالي<strong>${money(annualSaving)}</strong></div><div class="summary-box">توفير سنوي صافٍ<strong>${money(netAnnual)}</strong></div><div class="summary-box">فترة الاسترداد<strong>${fmt(payback,1)} سنة</strong></div><div class="summary-box">خفض CO₂ تقريبي<strong>${fmt(co2,1)} طن/سنة</strong></div></div><p class="muted">هذه النتائج تقديرية مبنية على ساعات الشمس والخسائر والتعرفة المدخلة، ويجب تحديثها بقياسات الموقع والفاتورة الفعلية قبل الاعتماد النهائي.</p></div></div>`}
function fieldR(k,l,v){return `<div class="field"><label>${l}</label><input id="r_${k}" type="number" step=".01" value="${v}"></div>`}window.updateReport=()=>{const p=getProject();p.report={tariff:Number($('#r_tariff').value),escalation:Number($('#r_escalation').value),maintenance:Number($('#r_maintenance').value)};save();report()};

function library(){const cats={all:'الكل',inverter:'إنفرترات',panel:'ألواح',battery:'بطاريات',dc:'حمايات DC',cable:'كابلات'};let cat='all';$('#content').innerHTML=`<div class="card"><div class="section-title"><h2>مكتبة المنتجات</h2><button class="primary" onclick="addProduct()">+ إضافة منتج</button></div><div class="tabs">${Object.entries(cats).map(([k,v])=>`<button class="tab ${k==='all'?'active':''}" onclick="filterProducts('${k}',this)">${v}</button>`).join('')}</div><div id="productTable"></div></div>`;renderProducts(cat)}
window.filterProducts=(cat,btn)=>{$$('.tab').forEach(x=>x.classList.remove('active'));btn.classList.add('active');renderProducts(cat)};function renderProducts(cat){const arr=cat==='all'?state.products:state.products.filter(x=>x.cat===cat);$('#productTable').innerHTML=`<div class="table-wrap"><table><thead><tr><th>الفئة</th><th>العلامة</th><th>الموديل</th><th>الوصف</th><th>الكلفة</th><th>البيع</th><th>المخزون</th><th></th></tr></thead><tbody>${arr.map(x=>`<tr><td>${x.cat}</td><td>${x.brand}</td><td><b>${x.model}</b></td><td>${x.name}</td><td>${money(x.cost)}</td><td>${money(x.sell)}</td><td>${x.stock}</td><td><button class="secondary" onclick="editProduct('${x.id}')">تعديل</button></td></tr>`).join('')}</tbody></table></div>`}
window.addProduct=()=>productDialog();window.editProduct=id=>productDialog(state.products.find(x=>x.id===id));function productDialog(prod={}){const cat=prompt('الفئة: inverter / panel / battery / dc / cable',prod.cat||'panel');if(!cat)return;const brand=prompt('العلامة التجارية',prod.brand||''),model=prompt('رقم الموديل',prod.model||''),name=prompt('الوصف',prod.name||''),cost=Number(prompt('كلفة الشراء',prod.cost||0)),sell=Number(prompt('سعر البيع',prod.sell||0)),stock=Number(prompt('المخزون',prod.stock||0));if(prod.id)Object.assign(prod,{cat,brand,model,name,cost,sell,stock});else state.products.push({id:uid(),cat,brand,model,name,cost,sell,stock});save();library();toast('تم حفظ المنتج')}

function settings(){const s=state.settings;$('#content').innerHTML=`<div class="card"><div class="section-title"><h2>إعدادات الشركة والتسعير</h2></div><div class="form-grid">${fieldSet('company','اسم الشركة',s.company)}${fieldSet('phone','الهاتف',s.phone)}${fieldSet('overhead','مصاريف غير مباشرة %',s.overhead*100,'number')}${fieldSet('profit','هامش ربح افتراضي %',s.profit*100,'number')}${fieldSet('tax','TVA افتراضية %',s.tax,'number')}</div><div class="actions"><button class="primary" onclick="saveSettings()">حفظ الإعدادات</button><button class="danger-btn" onclick="resetApp()">إعادة ضبط البيانات</button></div></div>`}function fieldSet(k,l,v,t='text'){return `<div class="field"><label>${l}</label><input id="s_${k}" type="${t}" value="${v}"></div>`}window.saveSettings=()=>{state.settings.company=$('#s_company').value;state.settings.phone=$('#s_phone').value;state.settings.overhead=Number($('#s_overhead').value)/100;state.settings.profit=Number($('#s_profit').value)/100;state.settings.tax=Number($('#s_tax').value);save();toast('تم حفظ الإعدادات')};window.resetApp=()=>{if(confirm('سيتم حذف جميع المشاريع والبيانات المحلية. متابعة؟')){localStorage.removeItem('icoolSolarPro');location.reload()}};

$('#newProjectBtn').onclick=newProject;$('#menuBtn').onclick=()=>$('.sidebar').classList.toggle('open');$('#printBtn').onclick=()=>window.print();$('#backupBtn').onclick=()=>{const b=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`icool-solar-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)};$('#restoreInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const rd=new FileReader();rd.onload=()=>{try{state=JSON.parse(rd.result);save();go('dashboard');toast('تم استيراد النسخة الاحتياطية')}catch{alert('ملف غير صالح')}};rd.readAsText(f)};
renderNav();render();
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
